version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: composer
    directory: /packages/symfony-bundle
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
