<?php

declare(strict_types=1);

namespace Biscuit\Auth;

use Biscuit\Exception\AuthorizationException;
use Biscuit\Exception\AuthorizerBuildException;
use Biscuit\Exception\RunLimitException;
use Biscuit\Exception\SnapshotException;
use Error;

/**
 * Checks authorization policies against a token.
 *
 * Created from {@see AuthorizerBuilder::build()} or
 * {@see AuthorizerBuilder::buildUnauthenticated()}.
 *
 * ```php
 * $authorizer = (new AuthorizerBuilder('allow if user("alice")'))->build($token);
 *
 * try {
 *     $matched = $authorizer->authorize();
 *     // $matched->getKind() === 'allow'
 * } catch (AuthorizationException $e) {
 *     $deniedBy = $e->getMatchedPolicy();
 *     $failedChecks = $e->getFailedChecks();
 * }
 * ```
 */
class Authorizer
{
    /**
     * Instances are obtained through {@see AuthorizerBuilder}.
     */
    private function __construct() {}

    /**
     * Returns the cumulative engine execution time in seconds, when available.
     *
     * Includes inference and subsequent authorization or query evaluation on this
     * authorizer. It excludes token verification, authorizer construction, and
     * PHP binding overhead, so it is not the duration of the last PHP call.
     *
     * Returns null before evaluation or if inference fails before recording a
     * duration. A rejected authorization can still have a recorded duration.
     * Restored snapshots may already carry a duration from earlier execution.
     * Reading this value never evaluates or resets the authorizer.
     */
    public function executionTime(): ?float
    {
        throw new Error('Biscuit\Auth\Authorizer::executionTime() should be implemented by the biscuit_php extension.');
    }

    /**
     * Returns the engine's recorded number of fact-generation iterations.
     *
     * Counts passes that produced new facts, excluding the final pass with no
     * new facts. Repeated authorization or queries may reuse completed inference
     * without increasing this count. Interrupted inference may leave a partial
     * count even when executionTime() is null. Snapshots preserve the count.
     * Reading this value never evaluates or resets the authorizer.
     */
    public function iterations(): int
    {
        throw new Error('Biscuit\Auth\Authorizer::iterations() should be implemented by the biscuit_php extension.');
    }

    /**
     * Returns the number of facts currently stored in the Datalog engine.
     *
     * Includes initial and derived facts. The same logical fact can be counted
     * more than once when stored under different origin sets. This is not the
     * number of results of a query, nor a count of facts generated by the last
     * call. Reading this value never evaluates or resets the authorizer.
     */
    public function factCount(): int
    {
        throw new Error('Biscuit\Auth\Authorizer::factCount() should be implemented by the biscuit_php extension.');
    }

    /**
     * Verifies the checks and policies.
     *
     * On success, returns the `allow` policy that matched. On failure,
     * throws an {@see AuthorizationException} carrying the matched `deny`
     * policy (when one matched) and the list of failed checks.
     *
     * @throws RunLimitException If a Datalog run limit is reached before a decision.
     * @throws AuthorizationException If a check fails or no `allow` policy matches.
     */
    public function authorize(): MatchedPolicy
    {
        throw new Error('Biscuit\Auth\Authorizer::authorize() should be implemented by the biscuit_php extension.');
    }

    /**
     * Runs a rule against the authorizer's Datalog engine and returns the
     * facts it produces. The query only sees facts from the authorizer and
     * the token's authority block.
     *
     * @return list<Fact>
     *
     * @throws RunLimitException If a Datalog run limit is reached.
     * @throws AuthorizerBuildException If the query cannot be executed.
     */
    public function query(Rule $rule): array
    {
        throw new Error('Biscuit\Auth\Authorizer::query() should be implemented by the biscuit_php extension.');
    }

    /**
     * Serializes the authorizer state to a base64 snapshot.
     *
     * @throws SnapshotException If the snapshot cannot be serialized.
     */
    public function base64Snapshot(): string
    {
        throw new Error(
            'Biscuit\Auth\Authorizer::base64Snapshot() should be implemented by the biscuit_php extension.',
        );
    }

    /**
     * Serializes the authorizer state to a raw snapshot.
     *
     * @return list<int>
     *
     * @throws SnapshotException If the snapshot cannot be serialized.
     */
    public function rawSnapshot(): array
    {
        throw new Error('Biscuit\Auth\Authorizer::rawSnapshot() should be implemented by the biscuit_php extension.');
    }

    /**
     * Restores an authorizer from a base64 snapshot.
     *
     * @throws SnapshotException If the snapshot cannot be deserialized.
     */
    public static function fromBase64Snapshot(string $input): Authorizer
    {
        throw new Error(
            'Biscuit\Auth\Authorizer::fromBase64Snapshot() should be implemented by the biscuit_php extension.',
        );
    }

    /**
     * Restores an authorizer from a raw snapshot (binary string).
     *
     * @throws SnapshotException If the snapshot cannot be deserialized.
     */
    public static function fromRawSnapshot(string $input): Authorizer
    {
        throw new Error(
            'Biscuit\Auth\Authorizer::fromRawSnapshot() should be implemented by the biscuit_php extension.',
        );
    }

    /**
     * Returns the authorizer content (facts, rules, checks, and policies)
     * as Datalog source code.
     */
    public function __toString(): string
    {
        throw new Error('Biscuit\Auth\Authorizer::__toString() should be implemented by the biscuit_php extension.');
    }
}
