<?php

declare(strict_types=1);

namespace Biscuit\BiscuitBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('biscuit');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('keys')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('public_key')
                            ->defaultNull()
                            ->info('Public key in hexadecimal format')
                        ->end()
                        ->scalarNode('private_key')
                            ->defaultNull()
                            ->info('Private key in hexadecimal format')
                        ->end()
                        ->scalarNode('public_key_file')
                            ->defaultNull()
                            ->info('Path to public key file')
                        ->end()
                        ->scalarNode('private_key_file')
                            ->defaultNull()
                            ->info('Path to private key file')
                        ->end()
                        ->enumNode('algorithm')
                            ->values(['ed25519', 'secp256r1'])
                            ->defaultValue('ed25519')
                            ->info('Cryptographic algorithm for key generation')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('token_extractor')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('header')
                                    ->defaultTrue()
                                    ->info('Extract token from Authorization header')
                                ->end()
                                ->scalarNode('cookie')
                                    ->defaultFalse()
                                    ->info('Cookie name to extract token from, or false to disable')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable token verification caching')
                        ->end()
                        ->scalarNode('pool')
                            ->defaultValue('cache.app')
                            ->info('Cache pool service ID')
                        ->end()
                        ->integerNode('ttl')
                            ->defaultValue(3600)
                            ->info('Cache TTL in seconds')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('revocation')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable token revocation checking')
                        ->end()
                        ->scalarNode('service')
                            ->defaultNull()
                            ->info('Revocation checker service ID')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('policies')
                    ->useAttributeAsKey('name')
                    ->scalarPrototype()->end()
                    ->info('Named policy strings for authorization')
                ->end()
                ->arrayNode('token_templates')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->arrayNode('facts')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog facts for the token')
                            ->end()
                            ->arrayNode('checks')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog checks for the token')
                            ->end()
                            ->arrayNode('rules')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog rules for the token')
                            ->end()
                        ->end()
                    ->end()
                    ->info('Token templates with facts, checks, and rules')
                ->end()
                ->arrayNode('block_templates')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->arrayNode('facts')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog facts for the attenuation block')
                            ->end()
                            ->arrayNode('checks')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog checks for the attenuation block')
                            ->end()
                            ->arrayNode('rules')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->info('Datalog rules for the attenuation block')
                            ->end()
                        ->end()
                    ->end()
                    ->info('Block templates applied during token attenuation')
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
