//! Regenerate the snapshots used by AuthorizerStatisticsTest:
//! cargo run --locked --example authorizer_statistics_fixtures
//!
//! Builders avoid the wall-clock-dependent values of a live authorization.
//! Explicit limits make failure cases reproducible without changing the PHP API.

use biscuit_auth::{Authorizer, AuthorizerBuilder, datalog::RunLimits};
use std::{error::Error, fs, path::Path, time::Duration};

fn main() -> Result<(), Box<dyn Error>> {
    let source = "a(1); b($x) <- a($x); allow if b(1);";
    let limits = RunLimits {
        max_time: Duration::from_secs(5),
        ..Default::default()
    };
    let mut fixtures = Vec::new();
    for (name, code, bounds) in [
        ("ample", source, limits.clone()),
        (
            "iterations",
            source,
            RunLimits {
                max_iterations: 1,
                ..limits.clone()
            },
        ),
        (
            "facts",
            source,
            RunLimits {
                max_facts: 2,
                ..limits.clone()
            },
        ),
        (
            "inference_timeout",
            source,
            RunLimits {
                max_time: Duration::ZERO,
                ..limits.clone()
            },
        ),
        (
            "authorization_timeout",
            "allow if true;",
            RunLimits {
                max_time: Duration::ZERO,
                ..limits.clone()
            },
        ),
        ("denied", "a(1); deny if true;", limits.clone()),
    ] {
        let snapshot = AuthorizerBuilder::new()
            .code(code)?
            .set_limits(bounds)
            .to_base64_snapshot()?;
        fixtures.push(format!("    '{name}' => '{snapshot}'"));
    }

    let mut snapshot = AuthorizerBuilder::new()
        .code(source)?
        .set_limits(limits)
        .build_unauthenticated()?
        .snapshot()?;
    snapshot.execution_time = 1_234_567_890;
    let known_time = Authorizer::from_snapshot(snapshot.clone())?.to_base64_snapshot()?;
    fixtures.push(format!("    'known_time' => '{known_time}'"));
    snapshot.world.iterations = u64::MAX;
    let overflow = Authorizer::from_snapshot(snapshot)?.to_base64_snapshot()?;
    fixtures.push(format!("    'iterations_overflow' => '{overflow}'"));

    let directory = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    fs::create_dir_all(&directory)?;
    fs::write(
        directory.join("authorizer-statistics.php"),
        format!(
            "<?php\n\n// Generated by examples/authorizer_statistics_fixtures.rs.\nreturn [\n{},\n];\n",
            fixtures.join(",\n")
        ),
    )?;
    Ok(())
}
